
[[plugins]]
<<<<<<< Updated upstream
repo = 'cespare/vim-toml'
on_ft = ['toml']

=======
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
hook_source = ''' " {{{
    " 自動で折りたたまないようにする
    let g:vim_markdown_folding_disabled = 1
''' # }}}
>>>>>>> Stashed changes

[[plugins]]
repo = 'kannokanno/previm'
depends = ['open-browser.vim']
on_ft = ['markdown']
hook_source = ''' " {{{
    " リアルタイムプレビューを有効化
    let g:previm_enable_realtime = 1
''' # }}}

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']
