[[plugins]]
repo = 'shougo/dein.vim'

[[plugins]]
repo = 'shougo/neocomplete.vim'
hook_add = ''' " {{{
    let g:neocomplete#enable_at_startup = 1
    let g:neocomplete#enable_smart_case = 1
    let g:neocomplete#sources#syntax#min_keyword_length = 3
    inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
    augroup omnicompletionneocompletecommands
        autocmd!
        autocmd filetype css setlocal omnifunc=csscomplete#completecss
        autocmd filetype html,markdown setlocal omnifunc=htmlcomplete#completetags
        autocmd filetype javascript setlocal omnifunc=javascriptcomplete#completejs
        autocmd filetype xml setlocal omnifunc=xmlcomplete#completetags
    augroup end
''' # }}}
# autocmd filetype python setlocal omnifunc=pythoncomplete#complete

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = ['unite.vim']
hook_add = ''' " {{{
    let g:vimfiler_force_overwrite_statusline = 0
    let g:vimfiler_as_default_explorer = 1
    noremap <silent> [unite]ff :<C-u>VimFilerBufferDir<CR>
''' # }}}

[[plugins]]
repo = 'tpope/vim-commentary'

# [[plugins]]
# repo = 'jistr/vim-nerdtree-tabs'

#Colors
[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'

[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]] #jellybeans
repo = 'https://github.com/nanotech/jellybeans.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'Yggdroot/indentLine'
